using Google.Apis.Auth.OAuth2;

namespace Tooark.Tests.Moq.Dto;

public class GcpCredentialDto
{
  public JsonCredentialParameters GCP { get; set; } = new JsonCredentialParameters()
  {
    Type = "service_account",
    ProjectId = "test-project",
    PrivateKeyId = "test-private",
    PrivateKey = "-----BEGIN PRIVATE KEY-----\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nABCDeFGHIJKLMnopqrsT9u1VWXYZABCDEFghijKlMnOPQrSTUVWXY/zAb234cDeF\nHIJklMnOPQ5RStuVwxyzA+b=\n-----END PRIVATE KEY-----\n",
    ClientEmail = "test-email",
    ClientId = "test-id",
    TokenUri = "test-uri",
    ClientSecret = "test-secret",
    UniverseDomain = "test-domain"
  };
}
