name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Defining main branch
      uses: actions/checkout@main

    - name: Set up .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        source-url: https://nuget.pkg.github.com/Grupo-Jacto/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build with .NET
      run: dotnet build --configuration Release

    - name: Tests with .NET
      run: dotnet test

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Publish the package to GPR
      run: dotnet nuget push Tooark/bin/Release/*.nupkg
