name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/Grupo-Jacto/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build with .NET
      run: dotnet build --configuration Release

    - name: Tests with .NET
      run: dotnet test

    - name: Create the package
      run: dotnet pack --configuration Release /p:NoWarn="1591"

    - name: Publish the package to GPR
      run: dotnet nuget push Tooark/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/Grupo-Jacto" --api-key ${{secrets.GITHUB_TOKEN}}
